spring:
  application:
   name: PhishingDetectionv2


  profiles:
    active: dev

    jpa:
      open-in-view: false

jwt:
  secret: ${Secret-KEY}
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
  password-reset-token-expiration: 900000
